_target_: src.taskmodules.span_clf_with_gazetteer.SpanClassificationWithGazetteerTaskModule

tokenizer_name_or_path: google/electra-large-discriminator
wiki_to_vec_file: ???
gazetteer_path: ???
use_efficient_gazetteer: False
entity_annotation: entities
single_sentence: False
sentence_annotation: sentences
padding: True
truncation: True
max_length: 128
pad_to_multiple_of: null
label_pad_token_id: -100
label_to_id: null
max_span_length: 8
