_target_: src.taskmodules.span_classification.SpanClassificationTaskModule

tokenizer_name_or_path: google/electra-large-discriminator
entity_annotation: entities
padding: True
truncation: True
max_length: 128
pad_to_multiple_of: null
label_pad_token_id: -100
label_to_id: null
