_target_: src.models.span_clf_with_gazetteer.SpanClassificationWithGazetteerModel

model_name_or_path: google/electra-large-discriminator
wiki_to_vec_file: ???
learning_rate: 1e-5
task_learning_rate: 1e-4
warmup_proportion: 0.1
ignore_index: 0
max_span_length: 8
span_length_embedding_dim: 150
freeze_model: False
layer_mean: False
augment_input: True
augment_mask_probability: 0.2
